sudo: required

language: php

php:
  - 7.0

before_script:
  - composer install --prefer-source
  - chmod +x ./bin/ci/before_build.sh
  - ./bin/ci/before_build.sh

script: make test

services:
  rabbitmq
